title: Epon mahtava maailma
author: Eppo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Epon maailma on FiveM serveri, jonka perustaja on yllätys yllätys Eppo.
  Täällä opettelen rakentamaan omaa maailmaa aivan uniikiksi.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
